# Lie database organized by categories - workplace excuses and lies
LIES = {
    "sick": [
        "I have a severe case of keyboard elbow and my doctor says I need 24 hours of rest",
        "My cat accidentally unplugged my alarm clock and I just woke up",
        "I'm experiencing temporary WiFi allergies and need to stay away from all networks today",
        "I ate some bad code last night and I'm feeling a bit buggy",
        "My car's GPS is broken and it only shows routes to the beach, so I might be late",
        "I have a dentist appointment to get my Bluetooth tooth checked",
        "I'm suffering from acute meeting fatigue and need a recovery day",
        "My smart home locked me in and I'm waiting for tech support to let me out",
        "I have a severe case of Monday-itis, even though it's Wednesday",
        "My doctor prescribed a mandatory Netflix day for stress relief, so I can't come in",
        "I think I caught a computer virus and now I'm feeling glitchy, need to reboot myself",
        "My alarm clock updated overnight and now it only rings in a different timezone",
        "I'm having an allergic reaction to early mornings, doctor's orders to sleep in",
        "My coffee machine broke and I can't function without it, literally impossible",
        "I woke up with a bad case of imposter syndrome and need a mental health day",
    ],
    "meeting": [
        "I have a conflicting meeting with my future self and it's non-negotiable",
        "My calendar just auto-declined due to an AI productivity optimization I set up",
        "I'm in a critical debugging session with a production issue that only I can see",
        "I have a standing meeting with my rubber duck and it's very important for my workflow",
        "My internet is unstable and I can only attend meetings that are cancelled",
        "I'm scheduled for a deep work block that was approved by the CEO's cat",
        "I have a recurring appointment with my code that can't be rescheduled",
        "My meeting quota for the week is already exceeded per company policy",
        "I'm in the middle of a 4-hour compilation and I literally can't leave my desk",
        "I have a conflict with my lunch meeting, which is with myself, sorry",
        "My camera stopped working and I can't fix it until after the meeting time, weird timing",
        "I'm in a flow state right now and interrupting it would cost the company 3 hours of productivity",
        "My headphones died and I can't hear anything, also can't find my backup pair anywhere",
        "I double-booked myself with a nap and the nap was scheduled first, can't cancel it",
        "I'm practicing inbox zero and meetings don't fit that methodology, you understand",
    ],
    "deadline": [
        "The code was working perfectly until Mercury went into retrograde, I swear",
        "I finished it on time but my computer decided to update for 6 hours",
        "The project is 90% done, and the remaining 90% should be quick, trust me",
        "I was waiting for the API documentation that doesn't exist yet",
        "My code is done but it's currently being reviewed by my imaginary senior developer",
        "The deadline was in a different timezone and I got confused, my bad",
        "I completed it but saved it in the cloud and the cloud is currently raining",
        "I was blocked by a dependency on a library that hasn't been invented yet",
        "The task took longer because I was following best practices from the future",
        "I finished early but then spent extra time making it too perfect, you know how it is",
        "I was about to submit it but then I found a typo and had to rewrite everything, obviously",
        "The deadline wasn't in my calendar so technically it doesn't count, right?",
        "I finished it but my dog ate my laptop charger and now it's dead, can't access the files",
        "I was waiting for inspiration to strike and it's still on its way, should be here soon",
        "I prioritized other tasks that seemed more urgent at the time, like organizing my desk",
    ],
    "remote": [
        "My office chair at home is ergonomically certified and I'm 300% more productive here",
        "I need to supervise a critical package delivery that contains work-related items",
        "My home internet is faster and I can deploy to production 10 seconds quicker from here",
        "I'm conducting an experiment on remote work efficiency and today is day 47",
        "My commute time is better spent on professional development, you know, sleeping",
        "I have a Zoom background that makes me look more professional than in-office",
        "My cat is my accountability partner and she works from home, so I should too",
        "The office coffee machine is broken and I can't function without my home setup",
        "I'm avoiding office germs to maintain peak performance for the team",
        "My plants need watering and they're critical to my work-life balance",
        "I set up a standing desk at home and my back has never felt better, can't go back now",
        "My home office has better lighting for video calls, makes me look more professional",
        "I'm testing the company's remote work policy to make sure it actually works, quality assurance",
        "My neighbor is doing construction and I need to be here to let them know when it's too loud",
        "I work better in my pajamas and the office has a strict dress code, productivity killer",
    ],
    "technical": [
        "I can't access the file because it's in a quantum superposition of done and not done",
        "The bug only appears on my machine, which means it's a feature everywhere else, right?",
        "I'm waiting for Stack Overflow to answer my question from 2019, still pending",
        "The code works on my machine, so it's clearly an infrastructure issue on your end",
        "I need to refactor the entire codebase before I can fix this typo, it's best practice",
        "The documentation I need is in a repository that was deleted in 2015",
        "I'm blocked by a circular dependency between my motivation and the deadline",
        "The test suite is passing, but only when I'm not looking at it, weird right?",
        "I need to upgrade 47 dependencies before I can change this one line, security reasons",
        "The issue is caused by a race condition between my keyboard and my brain",
        "My IDE crashed and took all my unsaved work with it, had to start from scratch",
        "The server is responding but in a language I don't understand, might be ancient Latin",
        "I'm getting a 418 error which means I'm a teapot, can't work under these conditions",
        "My code is compiling but it's taking longer than the heat death of the universe",
        "The bug is a feature request in disguise, I'm just ahead of the product roadmap",
    ],
    "manager": [
        "I was working so hard I forgot to update the ticket status, my bad",
        "I'm practicing agile methodology by adapting to changing priorities, like taking a break",
        "I was pair programming with myself and we had a disagreement, still resolving it",
        "I'm investing time in technical debt reduction, learning new memes and stuff",
        "I was researching industry best practices, you know, scrolling Twitter for insights",
        "I'm doing proactive bug prevention by not writing any code today, smart right?",
        "I was mentoring junior developers, helping my friend with their homework actually",
        "I'm optimizing my workflow by eliminating unnecessary productivity",
        "I was in a deep focus state and lost track of time, totally wasn't napping though",
        "I'm following the 80/20 rule: 80% thinking, 20% doing, 0% working, perfect balance",
        "I was attending a virtual conference, by virtual I mean I had the tab open while gaming",
        "I'm implementing a new productivity system I read about, still in the research phase",
        "I was networking with industry professionals on LinkedIn, definitely not scrolling memes",
        "I'm taking a proactive approach to work-life balance by prioritizing the life part today",
        "I was documenting my code but the documentation is in my head, will write it down eventually",
    ],
    "tech": [
        "I once debugged a production issue by staring at the server until it fixed itself, true story",
        "I wrote a script that automatically closes Jira tickets when no one's looking",
        "My code passed all tests because I commented out the failing ones temporarily, will fix later",
        "I accidentally pushed to main and blamed it on a junior developer, they'll never know",
        "I've been using the same Stack Overflow answer for 3 years across different projects",
        "I told the client the feature was in progress but I haven't even read the requirements yet",
        "I fixed the bug by reverting to an older version and pretending I wrote new code",
        "I estimated 2 weeks for a 2-hour task so I could play video games, worked perfectly",
        "I said I was refactoring but really I just renamed some variables and called it a day",
        "I claimed the server was down but I just didn't want to deploy on Friday, you understand",
        "I told my team I was researching solutions but I was actually watching YouTube tutorials",
        "I said the API was rate-limiting us but I just forgot to add the API key, oops",
        "I blamed the slow performance on the database when my code had an infinite loop",
        "I told them I needed a new MacBook Pro for performance but my old one works fine",
        "I said I was working late but I just left my Slack status on active and went home",
        "I copy-pasted code from GitHub and told everyone I wrote it from scratch, no one checked",
        "I said I was doing code review but I just clicked approve without reading anything",
        "I told them the feature would take a month but finished it in a day, bought myself time",
        "I claimed I was optimizing the algorithm but I just added a loading spinner to make it seem faster",
        "I said I was following TDD but I wrote all the code first and tests never, classic move",
    ],
    "random": [
        "I told my friend I was busy but I was just rewatching The Office for the 5th time",
        "I said I read the entire book but I only read the summary on Wikipedia, don't tell anyone",
        "I claimed I went to the gym but I just drove there and sat in the parking lot for an hour",
        "I told my parents I'm eating healthy but I had pizza for breakfast this morning",
        "I said I was stuck in traffic but I just didn't want to leave the house yet, needed more coffee",
        "I told them I didn't get their message but I read it and chose to ignore it, sorry not sorry",
        "I claimed my phone died but I just didn't want to answer their call right then",
        "I said I'm allergic to that food but I just don't like it, easier than explaining",
        "I told my boss I sent the email but it's still sitting in my drafts, will send it tomorrow",
        "I claimed I didn't see their text but I saw it 3 hours ago and forgot to reply",
        "I said I was on another call but I was actually making coffee, needed that caffeine",
        "I told them I'd call them back but I have no intention of doing so, honestly",
        "I claimed I was out of town but I was just avoiding them, staying home all weekend",
        "I said I already have plans but my only plan is to stay home and do nothing, perfect plan",
        "I told them I'm really busy this week but I've been binge-watching Netflix the whole time",
        "I said I was cleaning my apartment but I just moved the mess to a different room",
        "I told them I'd be there in 5 minutes but I haven't even left yet, still in bed",
        "I claimed I was on a diet but I ate an entire pizza last night, no regrets",
        "I said I was saving money but I just bought another thing I don't need online, worth it",
        "I told them I was listening but I zoned out 10 minutes ago, no idea what they said",
    ],
}
